package me.zhengjie.agent.tool.input;

/** 运营指标的唯一枚举入口，禁止模型提交任意字段或 SQL 表达式。 */
public enum MetricName {
    CUSTOMER_PROFILE_COUNT,
    ACTIVE_SERVICE_CUSTOMER_COUNT,
    ACTIVE_ORDER_COUNT,
    DAILY_SCHEDULED_CUSTOMER_COUNT,
    DAILY_VERIFIED_CUSTOMER_COUNT,
    DAILY_UNVERIFIED_CUSTOMER_COUNT,
    DAILY_UNSCHEDULED_CUSTOMER_COUNT,
    MEAL_PLAN_FAILURE_COUNT,
    EXPIRING_ORDER_COUNT
}
