CREATE TABLE IF NOT EXISTS `agent_form_draft` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '数据库主键',
  `draft_id` varchar(80) NOT NULL COMMENT '不可猜测的草稿业务标识',
  `draft_type` varchar(40) NOT NULL COMMENT '草稿类型',
  `schema_version` varchar(16) NOT NULL COMMENT '草稿协议版本',
  `status` varchar(20) NOT NULL COMMENT '草稿生命周期状态',
  `revision` int NOT NULL DEFAULT 1 COMMENT '乐观锁修订版本',
  `payload` longtext COMMENT '完整类型化草稿 JSON，包含敏感客户资料',
  `recognized_fields` text COMMENT '已识别的登记字段路径 JSON',
  `missing_fields` text COMMENT '待补充的登记字段路径 JSON',
  `warnings` text COMMENT '稳定告警码 JSON，不含敏感资料',
  `source_session_id` varchar(80) NOT NULL COMMENT '来源 Agent 会话 ID',
  `source_message_id` varchar(80) NOT NULL COMMENT '来源用户消息数据库标识',
  `source_client_message_id` varchar(80) NOT NULL COMMENT '来源用户消息幂等标识',
  `owner_user_id` bigint NOT NULL COMMENT '草稿所属客服用户 ID',
  `target_permission` varchar(80) NOT NULL COMMENT '目标表单新增权限',
  `converted_from` varchar(40) DEFAULT NULL COMMENT '非敏感流程转换来源',
  `expires_at` datetime NOT NULL COMMENT '草稿过期时间',
  `claimed_at` datetime DEFAULT NULL COMMENT '首次领取时间',
  `submitted_at` datetime DEFAULT NULL COMMENT '正式业务提交时间',
  `target_business_id` bigint DEFAULT NULL COMMENT '正式创建后的业务记录 ID',
  `create_by` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(255) DEFAULT NULL COMMENT '更新人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_del` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_form_draft_id` (`draft_id`),
  UNIQUE KEY `uk_agent_form_draft_create_idem` (`owner_user_id`,`source_session_id`,`source_client_message_id`),
  KEY `idx_agent_form_draft_expiry` (`status`,`expires_at`),
  KEY `idx_agent_form_draft_owner` (`owner_user_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 客户及订单表单辅助草稿';
