CREATE TABLE IF NOT EXISTS `agent_business_query_audit` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `operator` varchar(64) DEFAULT NULL COMMENT '客服账号',
  `session_id` varchar(64) NOT NULL COMMENT '会话ID',
  `request_id` varchar(64) NOT NULL COMMENT '请求链路ID',
  `query_domain` varchar(32) NOT NULL COMMENT '查询领域',
  `query_action` varchar(32) NOT NULL COMMENT '查询动作',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_code` varchar(64) DEFAULT NULL COMMENT '客户编号',
  `order_id` bigint DEFAULT NULL COMMENT '订单ID',
  `order_code` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `tool_names` varchar(512) DEFAULT NULL COMMENT '工具名称摘要JSON',
  `result_count` int NOT NULL DEFAULT 0 COMMENT '结果条数',
  `cached` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否命中同轮缓存',
  `partial` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否部分成功或截断',
  `failure_type` varchar(64) DEFAULT NULL COMMENT '稳定失败类型',
  `analysis_source` varchar(16) DEFAULT NULL COMMENT '分析来源',
  `analysis_confidence` decimal(5,4) DEFAULT NULL COMMENT '分析置信度',
  `clarification_required` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否要求澄清',
  `metric_codes` varchar(512) DEFAULT NULL COMMENT '指标代码JSON',
  `dimension_codes` varchar(512) DEFAULT NULL COMMENT '维度代码JSON',
  `unsupported_reason` varchar(64) DEFAULT NULL COMMENT '未支持原因',
  `answer_validation_result` varchar(16) NOT NULL DEFAULT 'VALID' COMMENT '回答校验结果',
  `cost_ms` bigint NOT NULL DEFAULT 0 COMMENT '查询耗时毫秒',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_agent_business_query_request` (`request_id`),
  KEY `idx_agent_business_query_session` (`session_id`),
  KEY `idx_agent_business_query_operator_time` (`operator`, `create_time`),
  KEY `idx_agent_business_query_customer` (`customer_id`, `customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能客服只读业务查询审计表';
