CREATE TABLE IF NOT EXISTS `agent_rule_gap` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `gap_type` varchar(64) NOT NULL COMMENT '缺口类型',
  `source_type` varchar(64) NOT NULL COMMENT '来源类型',
  `source_id` bigint DEFAULT NULL COMMENT '来源记录ID',
  `request_id` varchar(128) DEFAULT NULL COMMENT '请求链路ID',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `record_date` varchar(32) DEFAULT NULL COMMENT '诊断日期',
  `meal_type` varchar(32) DEFAULT NULL COMMENT '餐次',
  `predicted_reason_codes` text COMMENT '预测原因码JSON数组',
  `actual_reason_code` varchar(128) NOT NULL COMMENT '真实原因码',
  `accepted` varchar(32) DEFAULT NULL COMMENT '反馈结论',
  `gap_description` varchar(1024) DEFAULT NULL COMMENT '缺口说明',
  `occurrence_count` int NOT NULL DEFAULT 1 COMMENT '出现次数',
  `status` varchar(32) NOT NULL DEFAULT 'OPEN' COMMENT '状态',
  `owner` varchar(64) DEFAULT NULL COMMENT '处理人',
  `operator` varchar(64) DEFAULT NULL COMMENT '操作人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_agent_rule_gap_status` (`status`),
  KEY `idx_agent_rule_gap_type` (`gap_type`),
  KEY `idx_agent_rule_gap_reason` (`actual_reason_code`),
  KEY `idx_agent_rule_gap_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能排查规则缺口维护表';
