CREATE TABLE IF NOT EXISTS `agent_chat_session` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `session_id` varchar(64) NOT NULL COMMENT '会话ID',
  `title` varchar(120) DEFAULT NULL COMMENT '会话标题',
  `operator` varchar(64) DEFAULT NULL COMMENT '客服账号',
  `customer_id` bigint DEFAULT NULL COMMENT '当前会话客户ID',
  `customer_code` varchar(64) DEFAULT NULL COMMENT '当前会话客户编号',
  `record_date` varchar(20) DEFAULT NULL COMMENT '当前会话排查日期',
  `meal_type` varchar(20) DEFAULT NULL COMMENT '当前会话餐次',
  `stage` varchar(32) NOT NULL DEFAULT 'COLLECTING_SLOTS' COMMENT '会话阶段',
  `last_request_id` varchar(64) DEFAULT NULL COMMENT '最近一次请求ID',
  `last_summary` varchar(500) DEFAULT NULL COMMENT '最近诊断摘要',
  `last_message_time` datetime DEFAULT NULL COMMENT '最近消息时间',
  `archived` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否归档',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_chat_session_id` (`session_id`),
  KEY `idx_agent_chat_operator_time` (`operator`, `update_time`),
  KEY `idx_agent_chat_customer` (`customer_id`, `customer_code`),
  KEY `idx_agent_chat_archived` (`archived`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能排查聊天会话表';
