CREATE TABLE IF NOT EXISTS `agent_action_audit` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `request_id` varchar(128) DEFAULT NULL COMMENT '请求链路ID',
  `session_id` varchar(128) DEFAULT NULL COMMENT '会话ID',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `action_code` varchar(64) NOT NULL COMMENT '动作码',
  `action_title` varchar(128) DEFAULT NULL COMMENT '动作标题',
  `risk_level` varchar(16) DEFAULT NULL COMMENT '风险等级',
  `target_type` varchar(64) DEFAULT NULL COMMENT '目标对象类型',
  `target_id` varchar(128) DEFAULT NULL COMMENT '目标对象ID',
  `before_snapshot` text COMMENT '变更前快照JSON',
  `after_preview` text COMMENT '变更后预览JSON',
  `required_permission` varchar(128) DEFAULT NULL COMMENT '所需权限',
  `second_confirmed` tinyint(1) DEFAULT 0 COMMENT '是否完成二次确认',
  `status` varchar(64) NOT NULL COMMENT '执行状态',
  `success` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否成功',
  `failure_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `execution_result` text COMMENT '正式执行结果JSON',
  `operator` varchar(64) DEFAULT NULL COMMENT '操作人',
  `comment` varchar(512) DEFAULT NULL COMMENT '客服备注',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_action_audit_idempotency` (`idempotency_key`),
  KEY `idx_agent_action_audit_request` (`request_id`),
  KEY `idx_agent_action_audit_session` (`session_id`),
  KEY `idx_agent_action_audit_action` (`action_code`),
  KEY `idx_agent_action_audit_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能排查动作确认审计表';
