create table meal_plan (
    id bigint auto_increment primary key,
    record_date date not null,
    meal_type varchar(20) not null,
    total_count int not null default 0,
    success_count int not null default 0,
    fail_count int not null default 0,
    status varchar(20) not null default 'GENERATING',
    generate_time datetime not null,
    create_by varchar(64) default '',
    update_by varchar(64) default '',
    deleted bit(1) not null default b'0',
    create_time datetime default current_timestamp,
    update_time datetime default current_timestamp on update current_timestamp,
    index idx_record_date_meal_deleted (record_date, meal_type, deleted),
    index idx_generate_time (generate_time)
) engine=innodb default charset=utf8mb4;

create table meal_plan_customer (
    id bigint auto_increment primary key,
    meal_plan_id bigint not null,
    customer_id bigint not null,
    customer_name varchar(64) not null default '',
    phone varchar(20) not null default '',
    order_id bigint not null,
    parent_package_id bigint not null default 0,
    child_package_id bigint not null default 0,
    status tinyint not null default 0 comment '0=失败,1=成功',
    fail_reason varchar(255) default '',
    meat_required_count int not null default 0,
    veg_required_count int not null default 0,
    include_soup tinyint not null default 0,
    include_rice tinyint not null default 0,
    supplementary_main_count int not null default 0 comment '补主菜数量=max(0,主菜需求数-1)',
    supplementary_side_count int not null default 0 comment '补副菜数量=max(0,副菜需求数-1)',
    supplementary_veg_count int not null default 0 comment '补素菜数量=max(0,素菜需求数-1)',
    supplementary_rice_count int not null default 0 comment '补米饭数量=max(0,米饭需求数-1)',
    supplementary_soup_count int not null default 0 comment '补汤数量=max(0,汤需求数-1)',
    create_by varchar(64) default '',
    update_by varchar(64) default '',
    deleted bit(1) not null default b'0',
    create_time datetime default current_timestamp,
    update_time datetime default current_timestamp on update current_timestamp,
    index idx_meal_plan_id (meal_plan_id),
    index idx_customer_id (customer_id),
    index idx_order_id (order_id),
    index idx_meal_plan_order (meal_plan_id, order_id),
    index idx_meal_plan_status (meal_plan_id, status)
) engine=innodb default charset=utf8mb4;

create table meal_plan_customer_item (
    id bigint auto_increment primary key,
    customer_plan_id bigint not null,
    dish_type varchar(20) not null,
    dish_id int not null,
    dish_name varchar(64) not null default '',
    seq int not null default 1,
    is_replaced bit(1) not null default b'0' comment '是否发生了替换',
    original_dish_id int default null comment '原本想选的菜品ID',
    original_dish_name varchar(64) default '' comment '原本想选的菜品名称',
    replace_reason varchar(20) default '' comment '替换原因：ALLERGY-过敏，NOT_FOUND-当日不足，NEXT_DAY-次日回退',
    create_by varchar(64) default '',
    update_by varchar(64) default '',
    deleted bit(1) not null default b'0',
    create_time datetime default current_timestamp,
    update_time datetime default current_timestamp on update current_timestamp,
    index idx_customer_plan_id (customer_plan_id),
    index idx_dish_id (dish_id)
) engine=innodb default charset=utf8mb4;
