package me.zhengjie.agent.query.domain;

/**
 * Agent 可返回的业务指标。金额相关指标不得加入该枚举。
 */
public enum AgentQueryMetric {
    MEAL_BALANCE,
    ORDER_COUNT,
    ACTIVE_ORDER_COUNT,
    VERIFICATION_COUNT,
    REFUND_COUNT,
    DISH_COUNT,
    DAILY_SCHEDULED_CUSTOMER_COUNT,
    DAILY_VERIFIED_CUSTOMER_COUNT,
    DAILY_UNVERIFIED_CUSTOMER_COUNT,
    DAILY_EXPECTED_CUSTOMER_COUNT,
    DAILY_UNSCHEDULED_CUSTOMER_COUNT,
    ACTIVE_CUSTOMER_COUNT,
    EXPIRING_ORDER_COUNT,
    MEAL_PLAN_FAILURE_COUNT
}
